// NOODLERACK wrapper around the open-source Warps DSP (MIT, © Émilie Gillet)
// Exposes the meta-modulator (presented in-app as "TWIRL").
//
// Conventions:
// - External I/O sample rate: matches the AudioContext (48000 Hz). Warps does
//   its own internal 6x oversampling (kOversampling) with fixed FIR SRC
//   filters, so the absolute base rate only sets the internal oscillator
//   tuning — we Init at 48 kHz and feed native blocks directly, no 32k-style
//   rational resampling needed (unlike Clouds).
// - Block size: the engine's buffers are kMaxBlockSize = 96 frames; the
//   worklet hands us up to 128 frames per call, so we chunk in <=96 spans.
// - Audio I/O is a stereo pair: left = carrier (Modulator's input.l), right =
//   modulator (input.r). When carrier_shape != 0 the carrier is generated by
//   Warps' internal oscillator at `note`, and the left input becomes its
//   through-zero FM source (firmware behaviour).
// - The only output we surface is the main (modulated) output, ShortFrame.l;
//   the firmware's AUX output (the unprocessed sum / second oscillator) is
//   dropped for v1.
// - Easter-egg modes (frequency shifter, vocoder, bit-crusher dosing) are left
//   off: set_easter_egg(false), and algorithm is clamped below the 0.7 vocoder
//   crossover so only the six cross-modulation algorithms are reachable.
#include <cmath>
#include <cstring>

#include "warps/dsp/modulator.h"

using namespace warps;

static const int kMaxFrames = 128;  // per w_render call
static const int kBlock = 96;       // warps::kMaxBlockSize

static Modulator modulator;

// I/O buffers exposed to JS.
static float carrier_buf[kMaxFrames];
static float modulator_buf[kMaxFrames];
static float out_buf[kMaxFrames];

// Native staging blocks (int16 stereo frames).
static ShortFrame in_block[kBlock];
static ShortFrame out_block[kBlock];

static inline int16_t Float2Short(float x) {
  float s = x * 32767.0f;
  if (s < -32768.0f) s = -32768.0f;
  if (s > 32767.0f) s = 32767.0f;
  return static_cast<int16_t>(s);
}

static inline float Clamp01(float x) {
  return x < 0.0f ? 0.0f : (x > 1.0f ? 1.0f : x);
}

extern "C" {

void w_init() {
  modulator.Init(48000.0f);
  modulator.set_bypass(false);
  modulator.set_easter_egg(false);

  Parameters* p = modulator.mutable_parameters();
  p->channel_drive[0] = 0.8f;
  p->channel_drive[1] = 0.8f;
  p->modulation_algorithm = 0.0f;
  p->modulation_parameter = 0.5f;
  p->frequency_shift_pot = 0.5f;
  p->frequency_shift_cv = 0.0f;
  p->phase_shift = 0.0f;
  p->note = 48.0f;
  p->carrier_shape = 0;  // external carrier
}

float* w_inl() { return carrier_buf; }
float* w_inr() { return modulator_buf; }
float* w_out() { return out_buf; }

// algorithm: 0..1 morphs xfade -> fold -> analog ring -> digital ring -> XOR
//   -> comparator (clamped below the vocoder crossover).
// timbre: 0..1 (modulation_parameter / intensity).
// drive_a / drive_b: 0..1 input level + saturation per channel.
// shape: 0 = external carrier; 1..3 = internal oscillator (sine/tri/saw).
// note: carrier pitch in semitones (only used when shape != 0).
void w_render(float algorithm, float timbre, float drive_a, float drive_b,
              int shape, float note, int size) {
  if (size < 1) return;
  if (size > kMaxFrames) size = kMaxFrames;

  if (shape < 0) shape = 0;
  if (shape > 3) shape = 3;

  // Keep below the 0.7..0.75 vocoder transition so v1 stays in the six
  // cross-modulation algorithms.
  float algo = algorithm;
  if (algo < 0.0f) algo = 0.0f;
  if (algo > 0.74f) algo = 0.74f;

  Parameters* p = modulator.mutable_parameters();
  p->modulation_algorithm = algo;
  p->modulation_parameter = Clamp01(timbre);
  p->channel_drive[0] = Clamp01(drive_a);
  p->channel_drive[1] = Clamp01(drive_b);
  p->carrier_shape = shape;
  if (note < 0.0f) note = 0.0f;
  if (note > 120.0f) note = 120.0f;
  p->note = note;

  int n = 0;
  while (n < size) {
    int chunk = size - n;
    if (chunk > kBlock) chunk = kBlock;
    for (int i = 0; i < chunk; ++i) {
      in_block[i].l = Float2Short(carrier_buf[n + i]);
      in_block[i].r = Float2Short(modulator_buf[n + i]);
    }
    modulator.Process(in_block, out_block, chunk);
    for (int i = 0; i < chunk; ++i) {
      out_buf[n + i] = static_cast<float>(out_block[i].l) / 32768.0f;
    }
    n += chunk;
  }
}

}  // extern "C"
